name: pr-cd-test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: CI Step
        run: echo "CI running on PR"

      - name: CD Step (should NOT run in real pipeline)
        run: |
          cat README.md
